# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=64)),
                ('created_on', models.DateTimeField(verbose_name='creation date')),
                ('amended_by', models.CharField(max_length=64)),
                ('amended_on', models.DateTimeField(auto_now=True, verbose_name='revision date')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
