# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.CharField(choices=[('Y', 'UNDONE'), ('N', 'DONE')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
    ]
